---
- name: single test
  hosts: schema_registry
  run_once: true
  vars:
    confluent:
      bin_path: ''
    kafka:
      bootstrap_servers: ip-172-30-27-155.eu-west-1.compute.internal:9093
    topic:
      name: single-avro-v3
      partitions: 3
    admin:
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret";'
        ssl.truststore.location: /var/ssl/private/schema_registry.truststore.jks
        ssl.truststore.password: confluenttruststorepass
    producer:
      schema_registry_url: http://ip-172-30-43-43.eu-west-1.compute.internal:8081
      schema_registry_credentials: greta:greta-secret
      properties:
        # Schema Registry
        basic.auth.credentials.source: USER_INFO
        schema.registry.basic.auth.user.info: greta:greta-secret
        # Kafka
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret";'
        ssl.truststore.location: /var/ssl/private/schema_registry.truststore.jks
        ssl.truststore.password: confluenttruststorepass
        batch.size: 100
    consumer:
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret";'
        ssl.truststore.location: /var/ssl/private/control_center.truststore.jks
        ssl.truststore.password: confluenttruststorepass
        group.id: test-consumer-v1
  tasks:
    - import_tasks: tasks/kafka_topic.yml
      vars:
        client_properties: "{{admin.properties}}"

    - import_tasks: tasks/kafka_produce_avro.yml
      vars:
        client_properties: "{{producer.properties}}"

#   - import_tasks: tasks/kafka_consume.yml
#     vars:
#       client_properties: "{{consumer.properties}}"
  
