---
- name: single test
  hosts: control_center
  vars:
    confluent:
      bin_path: ''
    kafka:
      bootstrap_servers: ip-172-30-18-38.eu-west-1.compute.internal:9093
    topic:
      name: single-test-v1
      partitions: 3

    admin:
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret";'
        ssl.truststore.location: /var/ssl/private/control_center.truststore.jks
        ssl.truststore.password: confluenttruststorepass
    producer:
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret";'
        ssl.truststore.location: /var/ssl/private/control_center.truststore.jks
        ssl.truststore.password: confluenttruststorepass
        batch.size: 100
    consumer:
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret";'
        ssl.truststore.location: /var/ssl/private/control_center.truststore.jks
        ssl.truststore.password: confluenttruststorepass
        group.id: test-consumer-v1
  tasks:
    - import_tasks: tasks/kafka_topic.yml
      vars:
        client_properties: "{{admin.properties}}"

    - import_tasks: tasks/kafka_produce.yml
      vars:
        client_properties: "{{producer.properties}}"

    - import_tasks: tasks/kafka_consume.yml
      vars:
        client_properties: "{{consumer.properties}}"
  
