---
- name: prepare config file
  template:
    src: client.properties.j2
    dest: /tmp/producer.properties

- name: set input file
  copy:
    src: producer.test
    dest: /tmp/producer.test

- name: produce into kafka topic
  shell: "{{confluent.bin_path}}kafka-console-producer --bootstrap-server {{ kafka.bootstrap_servers }} --producer.config /tmp/producer.properties --topic {{topic.name}} < /tmp/producer.test"
  register: task

- debug: var=task.stdout_lines
- debug: var=task.stderr_lines
