---
- name: prepare config file
  template:
    src: client.properties.j2
    dest: /tmp/producer.properties

- name: perf produce into kafka topic
  shell: "{{confluent.bin_path}}kafka-producer-perf-test --producer-props bootstrap.servers={{ kafka.bootstrap_servers }} --producer.config /tmp/producer.properties --topic {{topic.name}} --num-records {{producer.num_records}} --throughput {{producer.throughput}} --record-size {{producer.record_size}} > /tmp/perf-producer.txt"
  register: task

- debug: var=task.stdout_lines
- debug: var=task.stderr_lines
