---
- name: prepare config file
  template:
    src: client.properties.j2
    dest: /tmp/consumer.properties

- name: perf consume into kafka topic
  shell: "{{confluent.bin_path}}kafka-consume-perf-test --bootstrap.server {{ kafka.bootstrap_servers }} --consumer.config /tmp/consumer.properties --topic {{topic.name}} --messages {{consumer.messages}} --num-fetch-threads {{consumer.num_fetch_threads}} --threads {{consumer.threads}}"
  register: task

- debug: var=task.stdout_lines
- debug: var=task.stderr_lines
