---
- name: Create group
  group:
    name: "{{prometheus_group}}"
    state: present

- name: Create user
  user:
    name: "{{prometheus_user}}"
    group: "{{prometheus_group}}"
    state: present

- name: Prepare destination directory
  file:
    path: "{{prometheus_home}}"
    owner: "{{prometheus_user}}"
    group: "{{prometheus_group}}"
    state: directory

- name: Unarchive package
  unarchive:
    src: "{{prometheus_url}}"
    dest: "{{prometheus_home}}"
    owner: "{{prometheus_user}}"
    group: "{{prometheus_group}}"
    remote_src: "{{prometheus_url_remote|bool}}"

- name: Prepare service
  template:
    src: prometheus.service.j2
    dest: "/etc/systemd/system/{{prometheus_service}}.service"
    owner: "{{prometheus_user}}"
    group: "{{prometheus_group}}"

- name: Restart service
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: "{{prometheus_service}}"
