---
- name: Create group
  group:
    name: "{{prometheus_node_exporter_group}}"
    state: present

- name: Create user
  user:
    name: "{{prometheus_node_exporter_user}}"
    group: "{{prometheus_node_exporter_group}}"
    state: present

- name: Prepare exporter destination
  file:
    path: "{{prometheus_node_exporter_home}}"
    owner: "{{prometheus_node_exporter_user}}"
    group: "{{prometheus_node_exporter_group}}"
    state: directory

- name: Unarchive packaged exporter
  unarchive:
    src: "{{prometheus_node_exporter_url}}"
    dest: "{{prometheus_node_exporter_home}}"
    owner: "{{prometheus_node_exporter_user}}"
    group: "{{prometheus_node_exporter_group}}"
    remote_src: "{{prometheus_node_exporter_url_remote|bool}}"

- name: Prepare service
  template:
    src: node_exporter.service.j2
    dest: "/etc/systemd/system/{{prometheus_node_exporter_service}}.service"
    owner: "{{prometheus_node_exporter_user}}"
    group: "{{prometheus_node_exporter_group}}"

- name: Restart service
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: "{{prometheus_node_exporter_service}}"
